spring.application.name=ms-pedidos
server.port=8080

# Conexión a MySQL (mismo contenedor que reservas)
spring.datasource.url=jdbc:mysql://mysql_servidor:3306/restaurante_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=clave_maestra_root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
