spring.application.name=ms-admin
server.port=8081

# Conexión a la DB
spring.datasource.url=jdbc:mysql://mysql_servidor:3306/restaurante_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=clave_maestra_root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true